export const filterCountry = country => {
    if (country.includes('China')) return 'China';
    if (country.includes('Taiwan')) return 'Taiwan';
    if (country.includes('Taipei')) return 'Taiwan';
    return country;
};

export const filterProvince = province => {
    if (province.includes(', AL')) return 'Alabama';
    if (province.includes(', AK')) return 'Alaska';
    if (province.includes(', AS')) return 'American Samoa';
    if (province.includes(', AZ')) return 'Arizona';
    if (province.includes(', AR')) return 'Arkansas';
    if (province.includes(', CA')) return 'California';
    if (province.includes(', CO')) return 'Colorado';
    if (province.includes(', CT')) return 'Connecticut';
    if (province.includes(', DE')) return 'Delaware';
    if (province.includes(', DC')) return 'District of Columbia';
    if (province.includes('D.C.')) return 'District of Columbia';
    if (province.includes(', FL')) return 'Florida';
    if (province.includes(', GA')) return 'Georgia';
    if (province.includes(', GU')) return 'Guam';
    if (province.includes(', HI')) return 'Hawaii';
    if (province.includes(', ID')) return 'Idaho';
    if (province.includes(', IL')) return 'Illinois';
    if (province.includes(', IN')) return 'Indiana';
    if (province.includes(', IA')) return 'Iowa';
    if (province.includes(', KS')) return 'Kansas';
    if (province.includes(', KY')) return 'Kentucky';
    if (province.includes(', LA')) return 'Louisiana';
    if (province.includes(', ME')) return 'Maine';
    if (province.includes(', MD')) return 'Maryland';
    if (province.includes(', MH')) return 'Marshall Islands';
    if (province.includes(', MA')) return 'Massachusetts';
    if (province.includes(', MI')) return 'Michigan';
    if (province.includes(', FM')) return 'Micronesia';
    if (province.includes(', MN')) return 'Minnesota';
    if (province.includes(', MS')) return 'Mississippi';
    if (province.includes(', MO')) return 'Missouri';
    if (province.includes(', MT')) return 'Montana';
    if (province.includes(', NE')) return 'Nebraska';
    if (province.includes(', NV')) return 'Nevada';
    if (province.includes(', NH')) return 'New Hampshire';
    if (province.includes(', NJ')) return 'New Jersey';
    if (province.includes(', NM')) return 'New Mexico';
    if (province.includes(', NY')) return 'New York';
    if (province.includes(', NC')) return 'North Carolina';
    if (province.includes(', ND')) return 'North Dakota';
    if (province.includes(', MP')) return 'Northern Marianas';
    if (province.includes(', OH')) return 'Ohio';
    if (province.includes(', OK')) return 'Oklahoma';
    if (province.includes(', OR')) return 'Oregon';
    if (province.includes(', PW')) return 'Palau';
    if (province.includes(', PA')) return 'Pennsylvania';
    if (province.includes(', PR')) return 'Puerto Rico';
    if (province.includes(', RI')) return 'Rhode Island';
    if (province.includes(', SC')) return 'South Carolina';
    if (province.includes(', SD')) return 'South Dakota';
    if (province.includes(', TN')) return 'Tennessee';
    if (province.includes(', TX')) return 'Texas';
    if (province.includes(', UT')) return 'Utah';
    if (province.includes(', VT')) return 'Vermont';
    if (province.includes(', VA')) return 'Virginia';
    if (province.includes('Virgin Islands')) return 'Virgin Islands';
    if (province.includes(', VI')) return 'Virgin Islands';
    if (province.includes(', WA')) return 'Washington';
    if (province.includes(', WV')) return 'West Virginia';
    if (province.includes(', WI')) return 'Wisconsin';
    if (province.includes(', WY')) return 'Wyoming';
    if (province.includes('Diamond Princess')) return 'Diamond Princess';
    if (province.includes('Grand Princess')) return 'Grand Princess';
    if (province.includes('Taiwan')) return 'Taipei';
    return province;
};
